# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"1\n\nGeoRequest\x12\x11\n\tlongitude\x18\x01 \x01(\x02\x12\x10\n\x08latitude\x18\x02 \x01(\x02\"#\n\x0bGeoResponse\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\"*\n\x0cHelloRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"<\n\x0cTimeResponse\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\t\x12\x0f\n\x02tz\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x05\n\x03_tz\"1\n\x0bTimeRequest\x12\x15\n\x08timezone\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_timezone2p\n\x10\x43urrentTimestamp\x12/\n\x0egetCurrentTime\x12\x0c.TimeRequest\x1a\r.TimeResponse\"\x00\x12+\n\x08sayHello\x12\r.HelloRequest\x1a\x0e.HelloResponse\"\x00\x32\x36\n\x0cGuessCountry\x12&\n\x03geo\x12\x0b.GeoRequest\x1a\x0c.GeoResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEOREQUEST._serialized_start=16
  _GEOREQUEST._serialized_end=65
  _GEORESPONSE._serialized_start=67
  _GEORESPONSE._serialized_end=102
  _HELLOREQUEST._serialized_start=104
  _HELLOREQUEST._serialized_end=146
  _HELLORESPONSE._serialized_start=148
  _HELLORESPONSE._serialized_end=180
  _TIMERESPONSE._serialized_start=182
  _TIMERESPONSE._serialized_end=242
  _TIMEREQUEST._serialized_start=244
  _TIMEREQUEST._serialized_end=293
  _CURRENTTIMESTAMP._serialized_start=295
  _CURRENTTIMESTAMP._serialized_end=407
  _GUESSCOUNTRY._serialized_start=409
  _GUESSCOUNTRY._serialized_end=463
# @@protoc_insertion_point(module_scope)
